In [84]:
import pyaudio
import numpy as np
import wave
import keyboard



In [98]:
def audio_capture():
    recorded_snippets = []
    while True:
        if keyboard.is_pressed('space'):
            break
        data = record_audio()
        total_sum = sum(np.sum(np.abs(arr)) for arr in data)
        if (total_sum > 200000):
            recorded_snippets.append(data)
        else:
            pass
    return recorded_snippets

def record_audio():
    chunk = 1024
    sample_format = pyaudio.paInt16
    channels = 1
    fs = 44100
    seconds = 3

    recorder = pyaudio.PyAudio()  # Create an interface to PortAudio

    print('Recording')

    stream = recorder.open(format=sample_format,
                    channels=channels,
                    rate=fs,
                    frames_per_buffer=chunk,
                    input=True)

    frames = []  # Initialize array to store frames


    counter = 0
    while (counter < 25):
        data = stream.read(chunk)
        numpydata = np.frombuffer(data, dtype=np.int16)
        frames.append(numpydata)
        if np.sum(np.abs(numpydata)) < 4000:
            counter+=1
        else:
            counter = 0
            
    return frames


In [100]:
frames = audio_capture()
frames

Recording
Recording
Recording
Recording
Recording
Recording
Recording
Recording
Recording


[[array([-3, -5, -7, ...,  7,  9, 10], dtype=int16),
  array([ 6,  2,  1, ...,  1,  0, -2], dtype=int16),
  array([-2, -3, -3, ...,  5,  5,  6], dtype=int16),
  array([ 8, 10, 10, ..., -5, -4, -2], dtype=int16),
  array([ 0, -1, -3, ...,  4,  4,  5], dtype=int16),
  array([4, 4, 4, ..., 1, 0, 0], dtype=int16),
  array([ 4,  6,  7, ..., -6, -7, -8], dtype=int16),
  array([ -9,  -9, -10, ...,  -4,  -5,  -5], dtype=int16),
  array([-3, -1, -1, ...,  6,  6,  6], dtype=int16),
  array([7, 9, 9, ..., 0, 3, 3], dtype=int16),
  array([3, 2, 0, ..., 8, 7, 6], dtype=int16),
  array([6, 7, 6, ..., 2, 3, 4], dtype=int16),
  array([5, 4, 2, ..., 0, 0, 0], dtype=int16),
  array([0, 1, 3, ..., 2, 2, 1], dtype=int16),
  array([ 1,  0, -1, ...,  0,  0, -1], dtype=int16),
  array([-2, -2, -4, ..., -1,  0,  1], dtype=int16),
  array([ 2,  1, -1, ..., -4, -4, -5], dtype=int16),
  array([-4, -2,  0, ..., -2, -2, -3], dtype=int16),
  array([-2, -2, -2, ..., -1, -1, -3], dtype=int16),
  array([-4, -5, -6, ..

In [101]:
len(frames)

4

In [106]:
# Save the recorded data as a WAV file
for i in range(len(frames)):
    wf = wave.open(f'test_audio/{i+1}.wav', 'wb')
    wf.setnchannels(1)
    wf.setsampwidth(pyaudio.PyAudio().get_sample_size(pyaudio.paInt16))
    wf.setframerate(44100)
    wf.writeframes(b''.join(frames[i]))
    wf.close()

In [73]:
import speech_recognition as sr

with sr.AudioFile('test.wav') as source:
    audio = sr.Recognizer().record(source)
    text = sr.Recognizer().recognize_google(audio)
    print("You said: " + text)

You said: hello my name is Alex what's your name
